### ISSUE TITLE
MIPS pre-built binaries are missing dvbcsa support

### ISSUE THREAD

**Issue by FritLP** [catalinii/minisatip#1239]
Such to some problems like unstable run e.g. with an older version of minisatip, i downloaded the newest version. Now i currently have the problem, that normal channels works fine, but private channels, like sky are down. 

Im using it on my VuSolo2 and started it with the following command:
./minisatip -b 50000:8192000 -B 8000 -R /usr/share/minisatip/html -x 8080 -o 192.168.178.40:9000 -G

This is the command i used already in the older version. The client connect successfully to oscam and when start a channel like sky, i can see in the oscam live log, that it should get up, but nothing. 

Can u help?

**Comment by catalinii** [comment]
1) does a different provider (except sky) work?
2) feel free to upload the logs of ./minisatip -f -l http,pmt 
And try to tune to an encrypted channel

**Comment by FritLP** [comment]
1. No, other provider doesnt work to. So its a general problem.
2. I will give u an log of minisatip, oscam, and a screen of the minisatip web ui. (attached files)

[LOG Minisatip.txt](https://github.com/user-attachments/files/21204856/LOG.Minisatip.txt)
<img width="1906" height="291" alt="Image" src="https://github.com/user-attachments/assets/2946dd51-feee-4b45-8a5c-79d8f19485d0" />
<img width="1104" height="207" alt="Image" src="https://github.com/user-attachments/assets/a6469b36-8cae-47e7-81f2-ce607aa05148" />

**Comment by catalinii** [comment]
Use one of the binaries from github. 

You are missing libdvbcsa from here: https://github.com/catalinii/libdvbcsa 

@Jalle19 should we just fail minisatip and put a meaningful error message?

**Comment by Jalle19** [comment]
Not really sure where a meaningful error message would be shown?

**Comment by catalinii** [comment]
To compile dvbcsa when using oscam?

**Comment by Jalle19** [comment]
The -o switch should not be available if dvbcsa support is not compiled in

**Comment by FritLP** [comment]
Ok. I was using the latest mips release from the github. I will try to cross compile it.

**Comment by Jalle19** [comment]
@catalinii maybe we should include dvbcsa support in the pre-built binaries?

**Comment by catalinii** [comment]
The pre-build binaries have dvbcsa included and it should work, this is just for folks compiling

**Comment by Jalle19** [comment]
He said he used the latest mips release from GitHub 🤷

**Comment by FritLP** [comment]
Yes, to this time Release "v2.0.0-beta.9: Don't close CI adapters" was the latest version.

Today I tried to Cross compile it on my ubuntu vm. After some mistakes it was ready. With dvbcsa and dvbca support. I started it without any problems and the log seems to be okay. In the oscam live log i have seen,that it connected via dvbapi.

So everything seems to be ok. But no devices are able to find the satip server. I dont know whats wrong. The Client is up, and the webinterface is reachable to. The WebUI is a little buggy again, but its closely anytime buggy.

**Comment by FritLP** [comment]
Currently i tried the new latest binarie. It seems to be without dvbcsa. 😅

<img width="789" height="251" alt="Image" src="https://github.com/user-attachments/assets/ea8c4052-f921-493a-9da5-777cd7e5a841" />

**Comment by Jalle19** [comment]
That's a bug then, it should be built in

**Comment by Jalle19** [comment]
From the MIPS build:

```
 configure:  == Checking OpenSSL == 
checking for openssl/aes.h... no
configure:  == Checking Embedded == 
checking for backtrace... yes
configure:  == Checking DVBCSA == 
checking for dvbcsa/dvbcsa.h... no
```

**Comment by Jalle19** [comment]
The builds have been fixed, let's close this

**Comment by FritLP** [comment]
It doesnt work for me. Still the same Problem. I used the latest release. I have to use the mips_musl, the normal mips not working at all.

<img width="881" height="234" alt="Image" src="https://github.com/user-attachments/assets/ee30b5e8-b78a-4dae-9116-5477c0c98927" />

@Jalle19

**Comment by Jalle19** [comment]
Can't believe how incredibly hard it is to build even a resemblance of a working binary for MIPS...

**Comment by Jalle19** [comment]
> The pre-build binaries have dvbcsa included and it should work, this is just for folks compiling

Seems this isn't true for MIPS binaries. The build has always been with -DDISABLE_DVBCSA, at least as far back as I bothered to check. Not sure how to fix, maybe we need to compile OpenSSL and libdvbcsa with zig as well to get everything right?
